[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false

[browser]
serverAddress = "localhost"
serverPort = 8501

[theme]
primaryColor = "#ff4b4b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
